# -*- coding: utf-8 -*-
"""edprog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10cGifgtVdRYUxDni0643UGGgfAXwuO1t
"""

import xml.etree.ElementTree as ET
tree = ET.parse('sumoTrace.txt')
root = tree.getroot()

# 最上位階層のタグ・中身
#print(root.tag,root.attrib)
# 子階層のタグ・中身
#for child in root:
#    print(child.tag)
#    print(child.attrib)
i=0
for vehicle in root.iter('vehicle'):
    if(i>=100):
      break
    print(vehicle.attrib)

import sys
from xml.etree.ElementTree import iterparse
import copy
Ldict={}

def SUMOTraceParser(FCDOutput):
    t=0
    i=0
    dict1={}
    doc = iterparse(FCDOutput, events=('start', 'end'))
    # Skip the root element
    event, root =  next(doc)
    for event, elem in doc:
        if event == 'start':
            if elem.tag == 'timestep':
                if t != float(elem.attrib['time']):
                   a=copy.copy(dict1)
                   Ldict[t]=a
                   dict1.clear()

                t = float(elem.attrib['time'])

            elif elem.tag == 'vehicle':
                lane =elem.attrib['lane']
                if lane in dict1:
                  n=dict1[lane]
                  n=n+1
                  dict1[lane]=n
                else:
                  dict1[lane]=1



        elif event == 'end':
            if elem.tag == 'timestep':
                elem.clear()
                root.clear()

###
if __name__=='__main__':

    #FCDOutput = 'fcdoutput.xml'
    FCDOutput = 'sumoTrace.txt'
    SUMOTraceParser(FCDOutput)
    print(Ldict)
